# Generated by Django 4.1.2 on 2022-11-08 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_logs_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 8, 15, 26, 55, 981334)),
        ),
    ]
